<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Echantillon extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Echantillon_model');
    } 

    /*
     * Listing of echantillon
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('echantillon/index?');
        $config['total_rows'] = $this->Echantillon_model->get_all_echantillon_count();
        $this->pagination->initialize($config);

        $data['echantillon'] = $this->Echantillon_model->get_all_echantillon($params);
        
        $data['_view'] = 'echantillon/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new echantillon
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('GRAPPE','GRAPPE','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'Equipe' => $this->input->post('Equipe'),
				'lregion' => $this->input->post('lregion'),
				'region' => $this->input->post('region'),
				'Envoi' => $this->input->post('Envoi'),
				'DateFinCOl' => $this->input->post('DateFinCOl'),
				'IDSE' => $this->input->post('IDSE'),
				'Denombrement' => $this->input->post('Denombrement'),
				'ASEGMENTER' => $this->input->post('ASEGMENTER'),
				'ANNEE' => $this->input->post('ANNEE'),
				'Fermeture' => $this->input->post('Fermeture'),
				'Localite' => $this->input->post('Localite'),
				'Contr' => $this->input->post('Contr'),
				'cercle' => $this->input->post('cercle'),
				'commune' => $this->input->post('commune'),
				'arrondissement' => $this->input->post('arrondissement'),
            );
            
            $echantillon_id = $this->Echantillon_model->add_echantillon($params);
            redirect('echantillon/index');
        }
        else
        {            
            $data['_view'] = 'echantillon/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a echantillon
     */
    function edit($GRAPPE)
    {   
        // check if the echantillon exists before trying to edit it
        $data['echantillon'] = $this->Echantillon_model->get_echantillon($GRAPPE);
        
        if(isset($data['echantillon']['GRAPPE']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('GRAPPE','GRAPPE','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'Equipe' => $this->input->post('Equipe'),
					'lregion' => $this->input->post('lregion'),
					'region' => $this->input->post('region'),
					'Envoi' => $this->input->post('Envoi'),
					'DateFinCOl' => $this->input->post('DateFinCOl'),
					'IDSE' => $this->input->post('IDSE'),
					'Denombrement' => $this->input->post('Denombrement'),
					'ASEGMENTER' => $this->input->post('ASEGMENTER'),
					'ANNEE' => $this->input->post('ANNEE'),
					'Fermeture' => $this->input->post('Fermeture'),
					'Localite' => $this->input->post('Localite'),
					'Contr' => $this->input->post('Contr'),
					'cercle' => $this->input->post('cercle'),
					'commune' => $this->input->post('commune'),
					'arrondissement' => $this->input->post('arrondissement'),
                );

                $this->Echantillon_model->update_echantillon($GRAPPE,$params);            
                redirect('echantillon/index');
            }
            else
            {
                $data['_view'] = 'echantillon/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The echantillon you are trying to edit does not exist.');
    } 

    /*
     * Deleting echantillon
     */
    function remove($GRAPPE)
    {
        $echantillon = $this->Echantillon_model->get_echantillon($GRAPPE);

        // check if the echantillon exists before trying to delete it
        if(isset($echantillon['GRAPPE']))
        {
            $this->Echantillon_model->delete_echantillon($GRAPPE);
            redirect('echantillon/index');
        }
        else
            show_error('The echantillon you are trying to delete does not exist.');
    }
    
}
