<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Passage extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->library('session');
        $this->load->library('form_validation');
        $this->load->model('Passage_model');
    } 

    /*
     * Listing of passage
     */
    function index()
    {
        if(!$_SESSION['add_passage'] OR !$_SESSION['edit_passage']){
            redirect('login');
        }

        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('passage/index?');
        $config['total_rows'] = $this->Passage_model->get_all_passage_count();
        $this->pagination->initialize($config);

        $data['passage'] = $this->Passage_model->get_all_passage($params);
        
        $data['_view'] = 'passage/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new passage
     */
    function add()
    {   
        if(!$_SESSION['add_passage']){
            redirect('login');
        }
        $id = $this->input->post('annee') . $this->input->post('passage');
        if($this->Passage_model->get_passage($id)){
            $this->session->set_flashdata('duplicate_id','Ce passage a déjà été ajouté.'); 
            $data['_view'] = 'passage/add';
            $this->load->view('admin/main',$data);
        }        

        //$annee = date('Y');
        
        $this->form_validation->set_rules('annee','ANNEE','required|exact_length[4]|greater_than[2019]',
            //array('required' => 'Le champ %s est obligatoire.')
        );
        $this->form_validation->set_rules('passage','PASSAGE','required|less_than[5]|greater_than[0]', 
            //array('required' => 'Le champ %s est obligatoire.')
        );
		
		if($this->form_validation->run())     
        {   
            $currentDateTime = date('Y-m-d H:i:s');            
            $params = array(
                'id' => $this->input->post('annee') . $this->input->post('passage'),
				'annee' => $this->input->post('annee'),
				'passage' => $this->input->post('passage'),
				'date_creation' => $currentDateTime,
				'date_maj' => $currentDateTime,				
            );
            
            $passage_id = $this->Passage_model->add_passage($params);
            redirect('passage/index');
        }
        else
        {            
            $data['_view'] = 'passage/add';
            $this->load->view('admin/main',$data);
        }
    }  

    /*
     * Editing a passage
     */
    function edit($id)
    {   
        // check if the passage exists before trying to edit it
        $data['passage'] = $this->Passage_model->get_passage($id);

        $currentDateTime = date('Y-m-d H:i:s');
        
        if(isset($data['passage']['id']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('annee','ANNEE','required|exact_length[4]|greater_than[2019]',
            //array('required' => 'Le champ %s est obligatoire.')
            );
            $this->form_validation->set_rules('passage','PASSAGE','required|less_than[5]|greater_than[0]', 
                //array('required' => 'Le champ %s est obligatoire.')
            );
			if($this->form_validation->run())     
            {   
                $params = array(
					'annee' => $this->input->post('annee'),
					'passage' => $this->input->post('passage'),
					'date_maj' => $currentDateTime,					
                );

                $this->Passage_model->update_passage($id,$params);            
                redirect('passage/index');
            }
            else
            {
                $data['_view'] = 'passage/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The passage you are trying to edit does not exist.');
    } 

    /*
     * Deleting passage
     */
    function remove($id)
    {
        $passage = $this->Passage_model->get_passage($id);

        // check if the passage exists before trying to delete it
        if(isset($passage['id']))
        {
            $this->Passage_model->delete_passage($id);
            redirect('passage/index');
        }
        else
            show_error('The passage you are trying to delete does not exist.');
    }
    
}
