<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Permissions_par_groupes_model extends CI_Model
{

    public $table = 'permissions_par_groupes';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_groupe', $q);
	$this->db->or_like('id_permission', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_groupe', $q);
	$this->db->or_like('id_permission', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_permissions_for_group($id)
    {
        $query = $this->db->query("SELECT 
            permissions.id AS id_p, permissions.code, 
            permissions.description, 
            permissions_par_groupes.id AS id_pg, 
            permissions_par_groupes.id_groupe 
        FROM permissions LEFT JOIN permissions_par_groupes 
        ON permissions.id=permissions_par_groupes.id_permission 
        WHERE 
            permissions_par_groupes.id_groupe=$id 
            OR permissions_par_groupes.id_groupe IS NULL");

        return $query->result_array();
    }

}

/* End of file Permissions_par_groupes_model.php */
/* Location: ./application/models/Permissions_par_groupes_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-24 21:11:55 */
/* http://harviacode.com */